/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PTrain.java
 *
 * Created on 12.09.2010, 17:20:34
 */
package routeFleet;

/**
 *
 * @author ЧерныхЕА
 */
import rzd.ModelTable;
public class PRoute extends javax.swing.JPanel {

    private Controller c;

    /** Creates new form PTrain */
    public PRoute() {
        initComponents();
        this.c = new Controller(this);
        bCreateTrain.addActionListener(c);
        tTarins.addMouseListener(c);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tTarins = new javax.swing.JTable();
        fSearchTainByNumber = new javax.swing.JTextField();
        bCreateTrain = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 243, 249));

        tTarins.setModel(new ModelTable() );
        tTarins.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tTarins);

        fSearchTainByNumber.setFont(new java.awt.Font("Tahoma", 2, 11));
        fSearchTainByNumber.setText("Поиск по номеру маршрута");

        bCreateTrain.setText("Создать маршрут");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fSearchTainByNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(bCreateTrain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSearchTainByNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCreateTrain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bCreateTrain;
    public javax.swing.JTextField fSearchTainByNumber;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tTarins;
    // End of variables declaration//GEN-END:variables
}
