/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CarInformation.java
 *
 * Created on 10.09.2010, 19:33:44
 */
package rzd.carFleet;

import javax.xml.ws.LogicalMessage;
import logic.BusinessLogic;
import rzd.model.Model;
import rzd.model.objects.Car;
import rzd.model.objects.CarLocation;
import rzd.model.objects.CarType;
import rzd.model.objects.Repair;
import rzd.model.objects.Route;
import rzd.model.objects.Train;

/**
 * @author ЧерныхЕА
 */
public class PCarInformation_1 extends javax.swing.JPanel {

    /**
     * Creates new form CarInformation
     */
    public PCarInformation_1() {
        initComponents();
    }

    public void setData(Car car) {
        if (car != null) {
            fNumberCar.setText(new Integer(car.getNumber()).toString());
            CarType carType = car.getCarType();
            CarType carParentType = Model.getModel().getCarParentType(carType);
            fTypeParent.setText(carParentType.getType());
            fTypeChilld.setText(carType.getType());
            fModelCar.setText(car.getModel());
            fConditioner.setText(car.getConditioner());
            fGenerator.setText(car.getGenerator());
            fGeneratorPrivod.setText(car.getGeneratorPrivod());
            fAccumulator.setText(car.getAccumulator());
            fElectricDevice.setText(car.getElectricDevice());
            fBodyColor.setText(car.getBodyColor());
            cEcologicCoilet.setSelected(car.isEcologicCoilet());
            fRunNorm.setText(new Integer(car.getRunNorm()).toString());
            fRun.setText(new Integer(car.getRun()).toString());
            fRunTozNorn.setText(new Integer(car.getRunTozNorm()).toString());
            fRunToz.setText(new Integer(car.getRunToz()).toString());
            CarLocation carLocation = car.getCarLocation();
            fLocation.setText(carLocation.getLocation());
            lLocOther.setVisible(true);
            fLocOther.setVisible(true);
            if (carLocation.getIdLocation() == BusinessLogic.UNKNOWN) {
                lLocOther.setVisible(false);
                fLocOther.setVisible(false);
            } else if (carLocation.getIdLocation() == BusinessLogic.REPAIR) {
                Repair repair = Model.getModel().getRepairByCar(car);
                lLocOther.setText("Тип ремонта");
                fLocOther.setText(repair.getRepairType().getType() + (repair.getRoad() != null ? " ; путь - " + repair.getRoad().getName() : ""));
            } else if (carLocation.getIdLocation() == BusinessLogic.ON_ROAD) {
                lLocOther.setText("Путь");
                fLocOther.setText(Model.getModel().getRoadByCar(car).getName());
            } else if (carLocation.getIdLocation() == BusinessLogic.IN_TRAIN) {
                lLocOther.setText("Поезд");
                Train train = Model.getModel().getTrainByCar(car);
                String route = "";
                if (train != null) {
                    if (train.getRoute().getSheduleForward().equals(train.getShedule())) {
                        route = train.getRoute().getNumberForward() + "  " + train.getRoute().getCityFrom() + " - " + train.getRoute().getCityTo();
                    }
                    if (train.getRoute().getSheduleBack().equals(train.getShedule())) {
                        route = train.getRoute().getNumberBack() + "  " + train.getRoute().getCityTo() + " - " + train.getRoute().getCityFrom();
                    }
                    fLocOther.setText(route);
                }

            }
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fConditioner = new javax.swing.JTextField();
        fModelCar = new javax.swing.JTextField();
        fGenerator = new javax.swing.JTextField();
        fGeneratorPrivod = new javax.swing.JTextField();
        fAccumulator = new javax.swing.JTextField();
        fElectricDevice = new javax.swing.JTextField();
        fBodyColor = new javax.swing.JTextField();
        cEcologicCoilet = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fTypeParent = new javax.swing.JTextField();
        fTypeChilld = new javax.swing.JTextField();
        fNumberCar = new javax.swing.JTextField();
        fRunNorm = new javax.swing.JTextField();
        fRunTozNorn = new javax.swing.JTextField();
        fRun = new javax.swing.JTextField();
        fRunToz = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fLocation = new javax.swing.JTextField();
        lLocOther = new javax.swing.JLabel();
        fLocOther = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Модель");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Вент/конд");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Генератор");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Привод генератора");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Аккумулятор");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Электрообоудование");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Окраска кузова");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Эколог., туалет");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Прбег (км) норма от пл. р.");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Прбег (км) норма от ТОЗ.");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Номер вагона");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Тип");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Подтип");

        fConditioner.setBackground(new java.awt.Color(255, 255, 255));
        fConditioner.setEditable(false);
        fConditioner.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fConditioner.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fConditioner.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        fModelCar.setBackground(new java.awt.Color(255, 255, 255));
        fModelCar.setEditable(false);
        fModelCar.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fModelCar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fModelCar.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        fGenerator.setBackground(new java.awt.Color(255, 255, 255));
        fGenerator.setEditable(false);
        fGenerator.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fGenerator.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fGenerator.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        fGeneratorPrivod.setBackground(new java.awt.Color(255, 255, 255));
        fGeneratorPrivod.setEditable(false);
        fGeneratorPrivod.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fGeneratorPrivod.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fGeneratorPrivod.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        fAccumulator.setBackground(new java.awt.Color(255, 255, 255));
        fAccumulator.setEditable(false);
        fAccumulator.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fAccumulator.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fAccumulator.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        fElectricDevice.setBackground(new java.awt.Color(255, 255, 255));
        fElectricDevice.setEditable(false);
        fElectricDevice.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fElectricDevice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fElectricDevice.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        fBodyColor.setBackground(new java.awt.Color(255, 255, 255));
        fBodyColor.setEditable(false);
        fBodyColor.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fBodyColor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fBodyColor.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        cEcologicCoilet.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Прбег (км) от пл. р.");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Прбег (км) от ТОЗ");

        fTypeParent.setBackground(new java.awt.Color(255, 255, 255));
        fTypeParent.setEditable(false);
        fTypeParent.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fTypeParent.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fTypeParent.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        fTypeChilld.setBackground(new java.awt.Color(255, 255, 255));
        fTypeChilld.setEditable(false);
        fTypeChilld.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fTypeChilld.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fTypeChilld.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        fNumberCar.setBackground(new java.awt.Color(255, 255, 255));
        fNumberCar.setEditable(false);
        fNumberCar.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fNumberCar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        fRunNorm.setBackground(new java.awt.Color(255, 255, 255));
        fRunNorm.setEditable(false);
        fRunNorm.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fRunNorm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        fRunTozNorn.setBackground(new java.awt.Color(255, 255, 255));
        fRunTozNorn.setEditable(false);
        fRunTozNorn.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fRunTozNorn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        fRun.setBackground(new java.awt.Color(255, 255, 255));
        fRun.setEditable(false);
        fRun.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fRun.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        fRunToz.setBackground(new java.awt.Color(255, 255, 255));
        fRunToz.setEditable(false);
        fRunToz.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fRunToz.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fRunToz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fRunTozActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Местоположение");

        fLocation.setBackground(new java.awt.Color(255, 255, 255));
        fLocation.setEditable(false);
        fLocation.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fLocation.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fLocation.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        lLocOther.setFont(new java.awt.Font("Times New Roman", 2, 13));
        lLocOther.setForeground(new java.awt.Color(102, 102, 102));
        lLocOther.setText("текст");

        fLocOther.setBackground(new java.awt.Color(255, 255, 255));
        fLocOther.setEditable(false);
        fLocOther.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fLocOther.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fLocOther.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Местоположение вагона");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Информация о вагоне");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Пробеги");

        jPanel1.setBackground(new java.awt.Color(100, 149, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Информация о вагоне");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel20)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fRunTozNorn)
                            .addComponent(fRunNorm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fRun)
                            .addComponent(fRunToz, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(lLocOther, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fLocOther)
                                    .addComponent(fLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNumberCar, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(fTypeParent, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(fTypeChilld, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(fModelCar, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(fConditioner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(fGeneratorPrivod, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(fAccumulator, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(fElectricDevice, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(cEcologicCoilet)
                                    .addComponent(fGenerator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(fBodyColor, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLocOther)
                    .addComponent(fLocOther, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fNumberCar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fTypeParent, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(fTypeChilld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fModelCar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fConditioner, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fGeneratorPrivod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fAccumulator, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fElectricDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fBodyColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cEcologicCoilet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fRunNorm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fRun, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fRunTozNorn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fRunToz, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fRunTozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fRunTozActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fRunTozActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.getParent().setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cEcologicCoilet;
    private javax.swing.JTextField fAccumulator;
    private javax.swing.JTextField fBodyColor;
    private javax.swing.JTextField fConditioner;
    private javax.swing.JTextField fElectricDevice;
    private javax.swing.JTextField fGenerator;
    private javax.swing.JTextField fGeneratorPrivod;
    private javax.swing.JTextField fLocOther;
    private javax.swing.JTextField fLocation;
    private javax.swing.JTextField fModelCar;
    private javax.swing.JTextField fNumberCar;
    private javax.swing.JTextField fRun;
    private javax.swing.JTextField fRunNorm;
    private javax.swing.JTextField fRunToz;
    private javax.swing.JTextField fRunTozNorn;
    private javax.swing.JTextField fTypeChilld;
    private javax.swing.JTextField fTypeParent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lLocOther;
    // End of variables declaration//GEN-END:variables
}
