/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContainerRoad.java
 *
 * Created on 09.09.2010, 16:25:50
 */

package rzd.tablo;

import java.awt.Point;

/**
 *
 * @author ЧерныхЕА
 */
public class ContainerRoad extends javax.swing.JPanel {

    /** Creates new form ContainerRoad */
    public ContainerRoad() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pContainerRoads = new javax.swing.JPanel();

        pContainer.setLayout(new javax.swing.BoxLayout(pContainer, javax.swing.BoxLayout.LINE_AXIS));

        pContainerRoads.setLayout(new javax.swing.BoxLayout(pContainerRoads, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(pContainerRoads);

        pContainer.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

public void addRoad(PRoad r){
    pContainerRoads.add(r);
}

public void removeRoad(PRoad r){
    pContainerRoads.remove(r);
}

public void setViewRoad(PRoad r){
    if(pContainerRoads.isAncestorOf(r)){
 jScrollPane1.getVerticalScrollBar().setValue((int)r.getLocation().getY());

        //     jScrollPane1.getViewport().setViewPosition(r.getLocation());
    }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pContainer;
    private javax.swing.JPanel pContainerRoads;
    // End of variables declaration//GEN-END:variables

}
