/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DEditTrain.java
 *
 * Created on 12.09.2010, 17:26:58
 */
package rzd.routeFleet;

import logic.BusinessLogic;
import rzd.model.objects.Route;

import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.StringTokenizer;
import javax.swing.*;

import rzd.model.objects.Shedule;
import rzd.model.objects.SheduleType;
import rzd.utils.Utils;

/**
 * @author ЧерныхЕА
 */
public class DRouteEdit extends javax.swing.JDialog {

    private ArrayList<SheduleType> sheduleTypes;
    private Route route;
    private JPopupMenu popupDayOfWeek;
    private JPopupMenu popupDayOfMonth;
    private PDayOfMonth pDayOfMonth;
    private PDaysOfWeek pDaysOfWeek;

    /**
     * Creates new form DEditTrain
     */
    public DRouteEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pDayOfMonth = new PDayOfMonth();
        pDaysOfWeek = new PDaysOfWeek();
        popupDayOfWeek = new JPopupMenu();
        popupDayOfMonth = new JPopupMenu();
        popupDayOfWeek.add(pDaysOfWeek);
        popupDayOfMonth.add(pDayOfMonth);
        for (int i = 0; i < 24; i++) {
            cHForward.addItem(i);
            cHBack.addItem(i);
        }
        for (int i = 0; i < 240; i++) {
            cHForwardInWay.addItem(i);
            cHBackInWay.addItem(i);
        }

        for (int i = 0; i < 60; i++) {
            cMForward.addItem(i);
            cMBack.addItem(i);
            cMForwardInWay.addItem(i);
            cMBackInWay.addItem(i);
        }

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLeft = new javax.swing.JPanel();
        bSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fNumberRoute1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fTimeForward = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        cTypeSchedule1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        fDaysMove1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fLengthForward = new javax.swing.JFormattedTextField();
        cHForward = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cMForward = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cHForwardInWay = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        cMForwardInWay = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        fStationDeparture = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fStationDestination = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        fNumberRoute2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fTimeBack = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        cTypeSchedule2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        fDaysMove2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fLengthBack = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cMBack = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        cHBack = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        cHBackInWay = new javax.swing.JComboBox();
        cMBackInWay = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        bCancel = new javax.swing.JButton();
        cEnabled = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Создание/редактирование расписания");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        bSave.setText("Сохранить");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)), "Следование из станции отпрвления в станцию назначения:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel7.setText("   Номер маршрута");
        jLabel7.setPreferredSize(new java.awt.Dimension(20, 14));

        fNumberRoute1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel3.setText("   Время отправления");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel8.setText("   Время в пути (в часах)");
        jLabel8.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel4.setText("   Время прибытия");
        jLabel4.setPreferredSize(new java.awt.Dimension(20, 14));

        fTimeForward.setEditable(false);
        fTimeForward.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel9.setText("   Тип следования");
        jLabel9.setPreferredSize(new java.awt.Dimension(20, 14));

        cTypeSchedule1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cTypeSchedule1ItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel11.setText("   Дни следования");
        jLabel11.setPreferredSize(new java.awt.Dimension(20, 14));

        fDaysMove1.setEditable(false);
        fDaysMove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fDaysMove1MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel17.setText("   Расстояние (км)");
        jLabel17.setPreferredSize(new java.awt.Dimension(20, 14));

        fLengthForward.setBackground(new java.awt.Color(255, 255, 204));
        fLengthForward.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        cHForward.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate1(evt);
            }
        });

        jLabel1.setText("-часы");

        cMForward.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate1(evt);
            }
        });

        jLabel2.setText("-мин");

        cHForwardInWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate1(evt);
            }
        });

        jLabel21.setText("-часы");

        cMForwardInWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate1(evt);
            }
        });

        jLabel22.setText("-мин");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(fNumberRoute1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(cTypeSchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(fDaysMove1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(fLengthForward, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fTimeForward, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cHForwardInWay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cHForward, 0, 61, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cMForwardInWay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cMForward, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNumberRoute1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHForward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cMForward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHForwardInWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(cMForwardInWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTimeForward, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTypeSchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fDaysMove1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fLengthForward, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        fStationDeparture.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel6.setText("   Станция отправления");
        jLabel6.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel16.setText("   Станция назначения");
        jLabel16.setPreferredSize(new java.awt.Dimension(20, 14));

        fStationDestination.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)), "Следование из станции назначения в станцию отпрвления:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel18.setText("   Номер маршрута");
        jLabel18.setPreferredSize(new java.awt.Dimension(20, 14));

        fNumberRoute2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel10.setText("   Время отправления");
        jLabel10.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel12.setText("   Время в пути (в часах)");
        jLabel12.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel14.setText("   Время прибытия");
        jLabel14.setPreferredSize(new java.awt.Dimension(20, 14));

        fTimeBack.setEditable(false);
        fTimeBack.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel13.setText("   Тип следования");
        jLabel13.setPreferredSize(new java.awt.Dimension(20, 14));

        cTypeSchedule2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cTypeSchedule2ItemStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel15.setText("   Дни следования");
        jLabel15.setPreferredSize(new java.awt.Dimension(20, 14));

        fDaysMove2.setEditable(false);
        fDaysMove2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fDaysMove2MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel19.setText("   Расстояние (км)");
        jLabel19.setPreferredSize(new java.awt.Dimension(20, 14));

        fLengthBack.setBackground(new java.awt.Color(255, 255, 204));
        fLengthBack.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("-мин");

        cMBack.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate2(evt);
            }
        });

        jLabel20.setText("-часы");

        cHBack.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate2(evt);
            }
        });

        jLabel23.setText("-часы");

        cHBackInWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate2(evt);
            }
        });

        cMBackInWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate2(evt);
            }
        });

        jLabel24.setText("-мин");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fDaysMove2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fLengthBack, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cHBack, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cHBackInWay, 0, 57, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cMBackInWay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cMBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(55, 55, 55))))
                            .addComponent(fNumberRoute2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fTimeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cTypeSchedule2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNumberRoute2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cMBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHBackInWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(cMBackInWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTimeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTypeSchedule2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fDaysMove2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fLengthBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        bCancel.setText("Отмена");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        cEnabled.setForeground(new java.awt.Color(255, 0, 0));
        cEnabled.setText("-активно");

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pLeftLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(fStationDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fStationDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pLeftLayout.createSequentialGroup()
                                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pLeftLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                                        .addComponent(bSave))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addComponent(cEnabled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addComponent(cEnabled)
                .addGap(7, 7, 7)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fStationDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fStationDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCancel))
                .addContainerGap())
        );

        getContentPane().add(pLeft);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        route = null;
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        route = null;
        setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed

    private void fDaysMove2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fDaysMove2MouseClicked
        if (fDaysMove2.isEnabled()) {
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                popupDayOfMonth.show(fDaysMove2, evt.getX(), evt.getY());
                pDayOfMonth.setSelectedDays(Utils.convertStrToMas(fDaysMove2.getText()), fDaysMove2);
            }
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                popupDayOfWeek.show(fDaysMove2, evt.getX(), evt.getY());
                pDaysOfWeek.setSelectedDays(Utils.convertDayOfWeekToMas(fDaysMove2.getText()), fDaysMove2);
            }
        }
    }//GEN-LAST:event_fDaysMove2MouseClicked

    private void fDaysMove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fDaysMove1MouseClicked
        if (fDaysMove1.isEnabled()) {
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                popupDayOfMonth.show(fDaysMove1, evt.getX(), evt.getY());
                pDayOfMonth.setSelectedDays(Utils.convertStrToMas(fDaysMove1.getText()), fDaysMove1);
            }
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                popupDayOfWeek.show(fDaysMove1, evt.getX(), evt.getY());
                pDaysOfWeek.setSelectedDays(Utils.convertDayOfWeekToMas(fDaysMove1.getText()), fDaysMove1);
            }
        }
    }//GEN-LAST:event_fDaysMove1MouseClicked

    private void cTypeSchedule1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cTypeSchedule1ItemStateChanged
        setEnabledSheduleType1();
    }//GEN-LAST:event_cTypeSchedule1ItemStateChanged

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        if (isCorrectInputData()) {
            int[] days = null;
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                days = Utils.convertStrToMas(fDaysMove1.getText());
            } else {
                if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                    days = Utils.convertDayOfWeekToMas(fDaysMove1.getText());
                }
            }
            Shedule s1 = new Shedule(route == null ? 0 : route.getSheduleForward().getId(),
                    Utils.convertStrToTime(cHForward.getSelectedItem().toString() + ":" + cMForward.getSelectedItem().toString()),
                    Utils.convertStrToTime(fTimeForward.getText().trim()),
                    Utils.convertStrToTime(cHForwardInWay.getSelectedItem().toString() + ":" + cMForwardInWay.getSelectedItem().toString()),
                    (SheduleType) cTypeSchedule1.getSelectedItem(),
                    days);
            days = null;
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                days = Utils.convertStrToMas(fDaysMove2.getText());
            } else {
                if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                    days = Utils.convertDayOfWeekToMas(fDaysMove2.getText());
                }
            }
            Shedule s2 = new Shedule(route == null ? 0 : route.getSheduleBack().getId(),
                    Utils.convertStrToTime(cHBack.getSelectedItem().toString() + ":" + cMBack.getSelectedItem().toString()),
                    Utils.convertStrToTime(fTimeBack.getText().trim()),
                    Utils.convertStrToTime(cHBackInWay.getSelectedItem().toString() + ":" + cMBackInWay.getSelectedItem().toString()),
                    (SheduleType) cTypeSchedule2.getSelectedItem(),
                    days);
            route = new Route(
                    route == null ? 0 : route.getId(),
                    fNumberRoute1.getText().trim(),
                    fNumberRoute2.getText().trim(),
                    fStationDeparture.getText().trim(),
                    fStationDestination.getText().trim(),
                    s1, s2, cEnabled.isSelected(),
                    new Integer(fLengthForward.getText()),
                    new Integer(fLengthBack.getText()));
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Заполните все поля");
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void updateDate1(java.awt.event.ItemEvent evt) {
        if (cMForward.getSelectedItem() != null && cMForwardInWay.getSelectedItem() != null && cHForward.getSelectedItem() != null && cHForwardInWay.getSelectedItem() != null) {
            int min = new Integer(cMForward.getSelectedItem().toString()) + new Integer(cMForwardInWay.getSelectedItem().toString());
            int hh = new Integer(cHForward.getSelectedItem().toString()) + new Integer(cHForwardInWay.getSelectedItem().toString());
            if (min > 59) {
                hh++;
                min = min - 60;
            }
            if (hh > 23) {
                hh = hh % 24;
            }
            fTimeForward.setText(new Integer(hh).toString() + ":" + new Integer(min).toString());
        }
    }

    private void updateDate2(java.awt.event.ItemEvent evt) {
        if (cMBack.getSelectedItem() != null && cMBackInWay.getSelectedItem() != null && cHBack.getSelectedItem() != null && cHBackInWay.getSelectedItem() != null) {
            int min = new Integer(cMBack.getSelectedItem().toString()) + new Integer(cMBackInWay.getSelectedItem().toString());
            int hh = new Integer(cHBack.getSelectedItem().toString()) + new Integer(cHBackInWay.getSelectedItem().toString());
            if (min > 59) {
                hh++;
                min = min - 60;
            }
            if (hh > 23) {
                hh = hh % 24;
            }
            fTimeBack.setText(new Integer(hh).toString() + ":" + new Integer(min).toString());
        }
    }

    private void cTypeSchedule2ItemStateChanged(java.awt.event.ItemEvent evt) {
        setEnabledSheduleType2();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DRouteEdit dialog = new DRouteEdit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Route open(Route route, ArrayList<SheduleType> sheduleTypes) {
        if (sheduleTypes == null) {
            JOptionPane.showMessageDialog(null, "Справочник типов расписаний пуст");
            return null;
        }
        this.route = route;
        this.sheduleTypes = sheduleTypes;
        cTypeSchedule1.removeAllItems();
        cTypeSchedule2.removeAllItems();
        for (SheduleType st : sheduleTypes) {
            cTypeSchedule2.addItem(st);
            cTypeSchedule1.addItem(st);
        }
        setEnabledSheduleType1();
        setEnabledSheduleType2();
        if (route == null) {
            fDaysMove1.setText("");
            fDaysMove2.setText("");
            cHForwardInWay.setSelectedIndex(0);
            cHBackInWay.setSelectedIndex(0);
            cMForwardInWay.setSelectedIndex(0);
            cMBackInWay.setSelectedIndex(0);
            cHForward.setSelectedIndex(0);
            cHBack.setSelectedIndex(0);
            cMForward.setSelectedIndex(0);
            cMBack.setSelectedIndex(0);
            fNumberRoute1.setText("");
            fNumberRoute2.setText("");
            fStationDeparture.setText("");
            fStationDestination.setText("");
            fTimeForward.setText("");
            fTimeBack.setText("");
            fLengthForward.setText("");
            fLengthBack.setText("");
            cEnabled.setSelected(true);

        } else {
            Shedule s1 = route.getSheduleForward();
            Shedule s2 = route.getSheduleBack();
            fStationDeparture.setText(route.getCityFrom());
            fStationDestination.setText(route.getCityTo());
            fNumberRoute1.setText(route.getNumberForward());
            fNumberRoute2.setText(route.getNumberBack());
            StringTokenizer t = new StringTokenizer(Utils.convertTimeToStr(s1.getTimeDeparture()), ":");
            String hh = t.nextToken();
            String mm = t.nextToken();
            cHForward.setSelectedItem(new Integer(hh));
            cMForward.setSelectedItem(new Integer(mm));
            t = new StringTokenizer(Utils.convertTimeToStr(s2.getTimeDeparture()), ":");
            hh = t.nextToken();
            mm = t.nextToken();
            cHBack.setSelectedItem(new Integer(hh));
            cMBack.setSelectedItem(new Integer(mm));
            t = new StringTokenizer(Utils.convertTimeToStr(s1.getTimeInWay()), ":");
            hh = t.nextToken();
            mm = t.nextToken();
            cHForwardInWay.setSelectedItem(new Integer(hh));
            cMForwardInWay.setSelectedItem(new Integer(mm));
            t = new StringTokenizer(Utils.convertTimeToStr(s2.getTimeInWay()), ":");
            hh = t.nextToken();
            mm = t.nextToken();
            cHBackInWay.setSelectedItem(new Integer(hh));
            cMBackInWay.setSelectedItem(new Integer(mm));
            fTimeForward.setText(Utils.convertTimeToStr(s1.getTimeDestination()));
            fTimeBack.setText(Utils.convertTimeToStr(s2.getTimeDestination()));
            cTypeSchedule1.setSelectedItem(s1.getScheduleType());
            cTypeSchedule2.setSelectedItem(s2.getScheduleType());
            if (s1.getScheduleType().getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove1.setText(Utils.convertMasToStr(s1.getDays()));
            }
            if (s1.getScheduleType().getId() == BusinessLogic.DAYS_WEEK) {
                fDaysMove1.setText(Utils.convertMasToDayOfWeek(s1.getDays()));
            }
            if (s2.getScheduleType().getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove2.setText(Utils.convertMasToStr(s2.getDays()));
            }
            if (s2.getScheduleType().getId() == BusinessLogic.DAYS_WEEK) {
                fDaysMove2.setText(Utils.convertMasToDayOfWeek(s2.getDays()));
            }
            fLengthForward.setText(new Integer(route.getLengthForward()).toString());
            fLengthBack.setText(new Integer(route.getLengthBack()).toString());
            cEnabled.setSelected(route.isEnabled());
        }
        setVisible(true);
        return this.route;
    }

    private void setEnabledSheduleType1() {
        if (cTypeSchedule1.getSelectedItem() != null) {
            fDaysMove1.setText("");
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK || ((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove1.setEnabled(true);
                fDaysMove1.setBackground(new Color(255, 255, 204));
            } else {
                fDaysMove1.setEnabled(false);
                fDaysMove1.setBackground(new Color(240, 240, 240));
            }
        }
    }

    private void setEnabledSheduleType2() {
        if (cTypeSchedule2.getSelectedItem() != null) {
            fDaysMove2.setText("");
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK || ((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove2.setEnabled(true);
                fDaysMove2.setBackground(new Color(255, 255, 204));
            } else {
                fDaysMove2.setEnabled(false);
                fDaysMove2.setBackground(new Color(240, 240, 240));

            }
        }
    }

    private boolean isCorrectInputData() {
        if (!fStationDeparture.getText().trim().equals("") &&
                !fStationDestination.getText().trim().equals("") &&
                !fNumberRoute1.getText().trim().equals("") &&
                !fNumberRoute2.getText().trim().equals("") &&
                !fTimeForward.getText().trim().equals("") &&
                !fTimeBack.getText().trim().equals("") &&
                (!fDaysMove1.isEnabled() || !fDaysMove1.getText().trim().equals("")) &&
                (!fDaysMove2.isEnabled() || !fDaysMove2.getText().trim().equals("")) &&
                !fLengthForward.getText().trim().equals("") &&
                !fLengthBack.getText().trim().equals("")) {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bCancel;
    public javax.swing.JButton bSave;
    private javax.swing.JCheckBox cEnabled;
    private javax.swing.JComboBox cHBack;
    private javax.swing.JComboBox cHBackInWay;
    private javax.swing.JComboBox cHForward;
    private javax.swing.JComboBox cHForwardInWay;
    private javax.swing.JComboBox cMBack;
    private javax.swing.JComboBox cMBackInWay;
    private javax.swing.JComboBox cMForward;
    private javax.swing.JComboBox cMForwardInWay;
    private javax.swing.JComboBox cTypeSchedule1;
    private javax.swing.JComboBox cTypeSchedule2;
    private javax.swing.JTextField fDaysMove1;
    private javax.swing.JTextField fDaysMove2;
    public javax.swing.JFormattedTextField fLengthBack;
    public javax.swing.JFormattedTextField fLengthForward;
    public javax.swing.JTextField fNumberRoute1;
    public javax.swing.JTextField fNumberRoute2;
    public javax.swing.JTextField fStationDeparture;
    public javax.swing.JTextField fStationDestination;
    public javax.swing.JFormattedTextField fTimeBack;
    public javax.swing.JFormattedTextField fTimeForward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pLeft;
    // End of variables declaration//GEN-END:variables
}
