/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DEditTrain.java
 *
 * Created on 18.09.2010, 19:16:47
 */
package rzd.dispStatinonFleet;

import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import logic.BusinessLogic;
import rzd.ControllerMain;
import rzd.ModelTable;
import rzd.carFleet.DCarLocation;
import rzd.model.Model;
import rzd.model.objects.*;
import rzd.utils.Utils;
import rzd.model.objects.structure.CarLocationStructure;

/**
 * @author Евгений
 */
public class DEditTrain extends javax.swing.JDialog {

    private Train train;
    private DCarLocation dCarLocation;

    /**
     * Creates new form DEditTrain
     */
    public DEditTrain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dCarLocation = new DCarLocation(null, true);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lDT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cRoad = new javax.swing.JComboBox();
        bSave = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fChief = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lCarAll = new javax.swing.JList(new DefaultListModel());
        bRight = new javax.swing.JButton();
        bLeft = new javax.swing.JButton();
        lbCarInTrain = new javax.swing.JLabel();
        lbCarAll = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cRoadType = new javax.swing.JComboBox();
        fRoute = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        fDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rHead = new javax.swing.JRadioButton();
        rHvost = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lCarInTrain = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(346, 239));

        lDT.setFont(new java.awt.Font("Times New Roman", 2, 13));
        lDT.setForeground(new java.awt.Color(82, 82, 82));
        lDT.setText("Дата и время");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel3.setForeground(new java.awt.Color(82, 82, 82));
        jLabel3.setText("Путь");

        cRoad.setFont(new java.awt.Font("Times New Roman", 0, 13));

        bSave.setText("Сохранить");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bCancel.setText("Отмена");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel4.setForeground(new java.awt.Color(82, 82, 82));
        jLabel4.setText("Начальник поезда");

        fChief.setFont(new java.awt.Font("Times New Roman", 0, 14));

        lCarAll.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lCarAll.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lCarAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showInfByCar(evt);
            }
        });
        jScrollPane2.setViewportView(lCarAll);

        bRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rzd/resurce/left.png"))); // NOI18N
        bRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRightActionPerformed(evt);
            }
        });

        bLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rzd/resurce/right.png"))); // NOI18N
        bLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLeftActionPerformed(evt);
            }
        });

        lbCarInTrain.setFont(new java.awt.Font("Times New Roman", 0, 13));
        lbCarInTrain.setForeground(new java.awt.Color(82, 82, 82));
        lbCarInTrain.setText("Вагоны в составе");

        lbCarAll.setFont(new java.awt.Font("Times New Roman", 0, 13));
        lbCarAll.setForeground(new java.awt.Color(82, 82, 82));
        lbCarAll.setText("Все вагоны");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 13));
        jLabel7.setForeground(new java.awt.Color(82, 82, 82));
        jLabel7.setText("Маршрут");

        cRoadType.setFont(new java.awt.Font("Times New Roman", 0, 13));
        cRoadType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cRoadTypeItemStateChanged(evt);
            }
        });

        fRoute.setBackground(new java.awt.Color(250, 250, 250));
        fRoute.setEditable(false);
        fRoute.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("*");

        fDate.setBackground(new java.awt.Color(250, 250, 250));
        fDate.setEditable(false);
        fDate.setFont(new java.awt.Font("Times New Roman", 0, 14));
        fDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel8.setForeground(new java.awt.Color(82, 82, 82));
        jLabel8.setText("Информация о поезде");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel9.setForeground(new java.awt.Color(82, 82, 82));
        jLabel9.setText("Отправление/прибытие");

        rHead.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(rHead);
        rHead.setSelected(true);
        rHead.setText(" - с головы");
        rHead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rHeadActionPerformed(evt);
            }
        });

        rHvost.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(rHvost);
        rHvost.setText(" - с хвоста");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel10.setForeground(new java.awt.Color(82, 82, 82));
        jLabel10.setText("Нумерация");

        lCarInTrain.setAutoCreateRowSorter(true);
        lCarInTrain.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lCarInTrain.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "П.Н", "Номер"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                    true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        lCarInTrain.setGridColor(new java.awt.Color(255, 255, 255));
        lCarInTrain.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lCarInTrain.getTableHeader().setReorderingAllowed(false);
        lCarInTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCarInTrainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lCarInTrain);
        lCarInTrain.getColumnModel().getColumn(0).setMinWidth(30);
        lCarInTrain.getColumnModel().getColumn(0).setPreferredWidth(30);
        lCarInTrain.getColumnModel().getColumn(0).setMaxWidth(30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(bSave)
                                                .addGap(18, 18, 18)
                                                .addComponent(bCancel))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fRoute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cRoad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cRoadType, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(fChief, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel43)))
                                        .addComponent(fDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rHead)
                                        .addComponent(rHvost)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bLeft, 0, 0, Short.MAX_VALUE)
                                        .addComponent(bRight, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lbCarInTrain))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbCarAll))
                        .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(fChief, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lDT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cRoadType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cRoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rHead)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rHvost)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bSave)
                                        .addComponent(bCancel)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(184, 184, 184)
                                        .addComponent(bRight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(249, 249, 249))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbCarInTrain)
                                        .addComponent(lbCarAll))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                        .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRightActionPerformed
        removeCarInTrain();

    }//GEN-LAST:event_bRightActionPerformed

    private void bLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLeftActionPerformed
        addCarInTrain();
    }//GEN-LAST:event_bLeftActionPerformed

    private void cRoadTypeItemStateChanged(java.awt.event.ItemEvent evt) {
        RoadType rt = (RoadType) cRoadType.getSelectedItem();
        cRoad.removeAllItems();
        if (rt != null) {
            ArrayList<Road> rr = Model.getModel().getRoadsByType(rt);
            if (rr != null && rr.size() != 0) {
                for (Road r : rr) {
                    cRoad.addItem(r);
                }
            }
        }
    }

    private void addCarInTrain() {
        Car car = (Car) lCarAll.getSelectedValue();
        if (car != null) {
            ((DefaultTableModel) lCarInTrain.getModel()).addRow(new Object[]{car.getCarNumberInTrain(), car});
            ((DefaultListModel) lCarAll.getModel()).removeElement(car);
        }
    }

    private void removeCarInTrain() {
        if (lCarInTrain.getSelectedRow() >= 0) {
            Car car = (Car) lCarInTrain.getValueAt(lCarInTrain.getSelectedRow(), 1);
            if (car != null) {
                boolean b = false;
                if (car.getCarLocation().getIdLocation() == BusinessLogic.IN_TRAIN) {
                    dCarLocation.setLocationRelativeTo(this);
                    CarLocationStructure carLS = dCarLocation.open(car);
                    if (carLS != null) {
                        try {
                            b = Model.getModel().setCarLocation(carLS.getCar(), carLS.getRoad(), carLS.getRepair());
                            if (b) {
                                car = carLS.getCar();
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, e.getMessage(), "Внимание", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                } else {
                    b = true;
                }
                if (b) {
                    ((DefaultListModel) lCarAll.getModel()).addElement(car);
                    for (int i = 0; i < ((DefaultListModel) lCarAll.getModel()).size(); i++) {
                        if (((DefaultTableModel) lCarInTrain.getModel()).getValueAt(i, 1).equals(car)) {
                            ((DefaultTableModel) lCarInTrain.getModel()).removeRow(i);
                            break;
                        }
                    }
                }
            }
        }
    }

    private void showInfByCar(java.awt.event.MouseEvent evt) {
        if (evt.getSource() instanceof JList && evt.getButton() == 1 && evt.getClickCount() == 2) {
            JList list = (JList) evt.getSource();
            Car car = ((Car) list.getSelectedValue());
            ControllerMain.getInstans().showCarInf(list, evt.getX() + 5, evt.getY() + 5, car);
        }
    }

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        save();
    }//GEN-LAST:event_bSaveActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        close();
    }//GEN-LAST:event_bCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();
    }//GEN-LAST:event_formWindowClosing

    private void rHeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rHeadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rHeadActionPerformed

    private void lCarInTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCarInTrainMouseClicked
        if (evt.getSource() instanceof JTable && evt.getButton() == 1 && evt.getClickCount() == 2) {
            JTable table = (JTable) evt.getSource();
            int row = table.getSelectedRow();
            if (row >= 0) {
                Car car = (Car) table.getValueAt(row, 1);
                ControllerMain.getInstans().showCarInf(table, evt.getX() + 5, evt.getY() + 5, car);
            }
        }
    }//GEN-LAST:event_lCarInTrainMouseClicked

    private void save() {
        if (isCorrectInput()) {
            if (Model.getModel().isRoadReadyForTrain(train, (Road) cRoad.getSelectedItem())) {
                ArrayList<Car> cars = new ArrayList<Car>(lCarInTrain.getModel().getRowCount());
                for (int i = 0; i < lCarInTrain.getModel().getRowCount(); i++) {
                    Car car = (Car) lCarInTrain.getModel().getValueAt(i, 1);
                    int pn = 0;
                    try {
                        pn = new Integer(lCarInTrain.getModel().getValueAt(i, 0).toString());
                    } catch (Exception e) {
                    }
                    car.setCarNumberInTrain(pn);
                    cars.add(car);
                }
                this.train = new Train(
                        train.getId(),
                        train.getDtDeparture(),
                        train.getDtDestination(),
                        fChief.getText().trim(),
                        train.getShedule(),
                        train.getRoute(),
                        train.getTrainStatus(),
                        (Road) cRoad.getSelectedItem(),
                        cars,
                        rHead.isSelected());
//                this.train = t;
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Путь занят, укажите другой путь", "Внимание...", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Заполните обязательные поля");
        }
    }

    private void close() {
        train = null;
        setVisible(false);
    }

    //Возаращеет Train,Route,Road,cars

    public Train open(Train train) {
        if (train == null) {
            close();
        }
        this.train = train;
        cRoadType.removeAllItems();
        cRoad.removeAllItems();
        RoadType rtTmp = null;
        //Запоняем справочники пути
        ArrayList<RoadType> roadTypes = Model.getModel().getRoadTypes();
        if (roadTypes == null) {
            JOptionPane.showMessageDialog(null, "Справочник путей пуст");
            return null;
        }
        for (RoadType roadType : roadTypes) {
            cRoadType.addItem(roadType);
        }
        if (train.getRoad() != null) {
            cRoadType.setSelectedItem(train.getRoad().getRoadType());
            ArrayList<Road> roads = Model.getModel().getRoadsByType(train.getRoad().getRoadType());
            for (Road road : roads) {
                cRoad.addItem(road);
            }
            cRoad.setSelectedItem(train.getRoad());
        }

        ((DefaultListModel) lCarAll.getModel()).removeAllElements();
        ArrayList<Car> carsAll = Model.getModel().getFreeCars();
        if (carsAll != null && carsAll.size() != 0) {
            for (Car c : carsAll) {
                // System.out.println(lCarAll.getModel().getClass().toString());
                ((DefaultListModel) lCarAll.getModel()).addElement(c);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Справочник вагонов пуст");
            return null;
        }

        ((DefaultTableModel) lCarInTrain.getModel()).setRowCount(0);
        if (train != null) {
            if (train.getRoute().getSheduleForward().equals(train.getShedule())) {
                lDT.setText("Дтата и время отправления");
                fDate.setText(Utils.convertDateTimeToStr(train.getDtDeparture()));
                fRoute.setText(train.getRoute().getNumberForward() + "  " + train.getRoute().getCityFrom() + " - " + train.getRoute().getCityTo());
            } else if (train.getRoute().getSheduleBack().equals(train.getShedule())) {
                lDT.setText("Дтата и время прибытия");
                fDate.setText(Utils.convertDateTimeToStr(train.getDtDestination()));
                fRoute.setText(train.getRoute().getNumberBack() + "  " + train.getRoute().getCityTo() + " - " + train.getRoute().getCityFrom());
            } else {
                JOptionPane.showMessageDialog(this, "Невозможно сопоставить с расписанием");
            }

            fChief.setText(train.getChief());
            ArrayList<Car> carsInTrain = train.getCarsIn();
            //если поезд без вагонов, то предлагаем дефолтовый состав вагонв
            if (carsInTrain == null) {
                ArrayList<Car> carsPlan = Model.getModel().getPlanCarForTrain(train);
                if (carsPlan != null) {
                    for (Car car : carsPlan) {
                        ((DefaultTableModel) lCarInTrain.getModel()).addRow(new Object[]{car.getCarNumberInTrain(), car});
                        ((DefaultListModel) lCarAll.getModel()).removeElement(car);
                    }
                }
            } else {
                //  System.out.println("Load cars in train="+carsInTrain.size());
                for (Car car : carsInTrain) {
                    ((DefaultTableModel) lCarInTrain.getModel()).addRow(new Object[]{car.getCarNumberInTrain(), car});
                }
            }
        }
        setVisible(true);
        return this.train;
    }

    private boolean isCorrectInput() {
        if (!fChief.getText().trim().equals("") &&
                !fDate.getText().trim().equals("") &&
                !fDate.getText().trim().equals("") &&
                cRoad.getSelectedItem() != null) {
            return true;
        } else {
            return false;
        }
    }
//    private ArrayList<Road> updateListRoad(RoadType rt){
//    H
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bLeft;
    private javax.swing.JButton bRight;
    private javax.swing.JButton bSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cRoad;
    private javax.swing.JComboBox cRoadType;
    private javax.swing.JTextField fChief;
    private javax.swing.JTextField fDate;
    private javax.swing.JTextField fRoute;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lCarAll;
    private javax.swing.JTable lCarInTrain;
    private javax.swing.JLabel lDT;
    private javax.swing.JLabel lbCarAll;
    private javax.swing.JLabel lbCarInTrain;
    private javax.swing.JRadioButton rHead;
    private javax.swing.JRadioButton rHvost;
    // End of variables declaration//GEN-END:variables
}
