/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DEditTrain.java
 *
 * Created on 12.09.2010, 17:26:58
 */
package rzd.routeFleet;

import logic.BusinessLogic;
import rzd.model.objects.Route;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;

import rzd.model.objects.Shedule;
import rzd.model.objects.SheduleType;
import rzd.utils.Utils;

/**
 * @author ЧерныхЕА
 */
public class DEditRoute extends javax.swing.JDialog {

    private ArrayList<SheduleType> sheduleTypes;
    private Route route;
    private JPopupMenu popupDayOfWeek;
    private JPopupMenu popupDayOfMonth;
    private PDayOfMonth pDayOfMonth;
    private PDaysOfWeek pDaysOfWeek;

    /**
     * Creates new form DEditTrain
     */
    public DEditRoute(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pDayOfMonth = new PDayOfMonth();
        pDaysOfWeek = new PDaysOfWeek();
        popupDayOfWeek = new JPopupMenu();
        popupDayOfMonth = new JPopupMenu();
        popupDayOfWeek.add(pDaysOfWeek);
        popupDayOfMonth.add(pDayOfMonth);

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLeft = new javax.swing.JPanel();
        bSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fNumberRoute1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fTimeDeparture1 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        fHourMove1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        fTimeDestination1 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        cTypeSchedule1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        fDaysMove1 = new javax.swing.JTextField();
        fStationDeparture = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fStationDestination = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        fNumberRoute2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fTimeDeparture2 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        fHourMove2 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        fTimeDestination2 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        cTypeSchedule2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        fDaysMove2 = new javax.swing.JTextField();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Создание/редактирование расписания");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        bSave.setText("Сохранить");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)), "Следование из станции отпрвления в станцию назначения:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setText("   Номер маршрута");
        jLabel7.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setText("   Время отправления");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 14));

        fTimeDeparture1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setText("   Время в пути (в часах)");
        jLabel8.setPreferredSize(new java.awt.Dimension(20, 14));

        fHourMove1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setText("   Время прибытия");
        jLabel4.setPreferredSize(new java.awt.Dimension(20, 14));

        fTimeDestination1.setEditable(false);
        fTimeDestination1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setText("   Тип следования");
        jLabel9.setPreferredSize(new java.awt.Dimension(20, 14));

        cTypeSchedule1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cTypeSchedule1ItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel11.setText("   Дни следования");
        jLabel11.setPreferredSize(new java.awt.Dimension(20, 14));

        fDaysMove1.setEditable(false);
        fDaysMove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fDaysMove1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(fNumberRoute1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(fDaysMove1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(cTypeSchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(fTimeDestination1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(fHourMove1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(fTimeDeparture1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNumberRoute1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTimeDeparture1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fHourMove1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTimeDestination1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTypeSchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fDaysMove1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setText("   Станция отправления");
        jLabel6.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setText("   Станция назначения");
        jLabel16.setPreferredSize(new java.awt.Dimension(20, 14));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)), "Следование из станции назначения в станцию отпрвления:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel18.setText("   Номер маршрута");
        jLabel18.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel10.setText("   Время отправления");
        jLabel10.setPreferredSize(new java.awt.Dimension(20, 14));

        fTimeDeparture2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel12.setText("   Время в пути (в часах)");
        jLabel12.setPreferredSize(new java.awt.Dimension(20, 14));

        fHourMove2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel14.setText("   Время прибытия");
        jLabel14.setPreferredSize(new java.awt.Dimension(20, 14));

        fTimeDestination2.setEditable(false);
        fTimeDestination2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel13.setText("   Тип следования");
        jLabel13.setPreferredSize(new java.awt.Dimension(20, 14));

        cTypeSchedule2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cTypeSchedule2ItemStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel15.setText("   Дни следования");
        jLabel15.setPreferredSize(new java.awt.Dimension(20, 14));

        fDaysMove2.setEditable(false);
        fDaysMove2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fDaysMove2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(fNumberRoute2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(fTimeDeparture2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(fHourMove2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(fTimeDestination2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(cTypeSchedule2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(fDaysMove2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNumberRoute2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTimeDeparture2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fHourMove2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTimeDestination2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTypeSchedule2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fDaysMove2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        bCancel.setText("Отмена");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(fStationDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fStationDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fStationDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fStationDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCancel))
                .addContainerGap())
        );

        getContentPane().add(pLeft);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        route = null;
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        route = null;
        setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed

    private void fDaysMove2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fDaysMove2MouseClicked
        if (fDaysMove2.isEnabled()) {
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                popupDayOfMonth.show(fDaysMove2, evt.getX(), evt.getY());
                pDayOfMonth.setSelectedDays(Utils.convertStrToMas(fDaysMove2.getText()), fDaysMove2);
            }
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                popupDayOfWeek.show(fDaysMove2, evt.getX(), evt.getY());
                pDaysOfWeek.setSelectedDays(Utils.convertDayOfWeekToMas(fDaysMove2.getText()), fDaysMove2);
            }
        }
    }//GEN-LAST:event_fDaysMove2MouseClicked

    private void fDaysMove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fDaysMove1MouseClicked
        if (fDaysMove1.isEnabled()) {
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                popupDayOfMonth.show(fDaysMove1, evt.getX(), evt.getY());
                pDayOfMonth.setSelectedDays(Utils.convertStrToMas(fDaysMove1.getText()), fDaysMove1);
            }
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                popupDayOfWeek.show(fDaysMove1, evt.getX(), evt.getY());
                pDaysOfWeek.setSelectedDays(Utils.convertDayOfWeekToMas(fDaysMove1.getText()), fDaysMove1);
            }
        }
}//GEN-LAST:event_fDaysMove1MouseClicked

    private void cTypeSchedule1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cTypeSchedule1ItemStateChanged
        setEnabledSheduleType();
}//GEN-LAST:event_cTypeSchedule1ItemStateChanged

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        if (isCorrectInputData()) {
            int[] days = null;
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                days = Utils.convertStrToMas(fDaysMove1.getText());
            } else {
                if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                    days = Utils.convertDayOfWeekToMas(fDaysMove1.getText());
                }
            }
            Shedule s1 = new Shedule(route == null ? 0 : route.getScheduleForward().getId(),
                    Utils.convertStrToTime(fTimeDeparture1.getText().trim()),
                    Utils.convertStrToTime(fTimeDestination1.getText().trim()),
                    Utils.convertStrToTime(fHourMove1.getText().trim()),
                    (SheduleType) cTypeSchedule1.getSelectedItem(),
                    days);
            days = null;
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                days = Utils.convertStrToMas(fDaysMove2.getText());
            } else {
                if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                    days = Utils.convertDayOfWeekToMas(fDaysMove2.getText());
                }
            }
            Shedule s2 = new Shedule(route == null ? 0 : route.getScheduleBack().getId(),
                    Utils.convertStrToTime(fTimeDeparture2.getText().trim()),
                    Utils.convertStrToTime(fTimeDestination2.getText().trim()),
                    Utils.convertStrToTime(fHourMove2.getText().trim()),
                    (SheduleType) cTypeSchedule2.getSelectedItem(),
                    days);
            route = new Route(
                    route == null ? 0 : route.getId(),
                    fNumberRoute1.getText().trim(),
                    fNumberRoute2.getText().trim(),
                    fStationDeparture.getText().trim(),
                    fStationDestination.getText().trim(),
                    s1, s2);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Заполните все поля");
        }
}//GEN-LAST:event_bSaveActionPerformed

    private void cTypeSchedule2ItemStateChanged(java.awt.event.ItemEvent evt) {
        setEnabledSheduleType();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DEditRoute dialog = new DEditRoute(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Route open(Route route, ArrayList<SheduleType> sheduleTypes) {
        if (sheduleTypes == null) {
            JOptionPane.showMessageDialog(null, "Справочник типов расписаний пуст");
            return null;
        }
        this.route = route;
        this.sheduleTypes = sheduleTypes;
        cTypeSchedule1.removeAllItems();
        cTypeSchedule2.removeAllItems();
        for (SheduleType st : sheduleTypes) {
            cTypeSchedule2.addItem(st);
            cTypeSchedule1.addItem(st);
        }
        if (route == null) {
            fDaysMove1.setText("");
            fDaysMove2.setText("");
            fHourMove2.setText("");
            fHourMove2.setText("");
            fNumberRoute1.setText("");
            fNumberRoute2.setText("");
            fStationDeparture.setText("");
            fStationDestination.setText("");
            fTimeDeparture1.setText("");
            fTimeDeparture2.setText("");
            fTimeDestination1.setText("");
            fTimeDestination2.setText("");
        } else {
            Shedule s1 = route.getScheduleForward();
            Shedule s2 = route.getScheduleBack();
            fStationDeparture.setText(route.getPointDeparture());
            fStationDestination.setText(route.getPointDestination());
            fNumberRoute1.setText(route.getNumberForward());
            fNumberRoute2.setText(route.getNumberBack());
            fTimeDeparture1.setText(Utils.convertTimeToStr(s1.getTimeDeparture()));
            fTimeDeparture2.setText(Utils.convertTimeToStr(s2.getTimeDeparture()));
            fHourMove1.setText(Utils.convertTimeToStr(s1.getTimeInWay()));
            fHourMove2.setText(Utils.convertTimeToStr(s2.getTimeInWay()));
            fTimeDestination1.setText(Utils.convertTimeToStr(s1.getTimeDestination()));
            fTimeDestination2.setText(Utils.convertTimeToStr(s2.getTimeDestination()));
            cTypeSchedule1.setSelectedItem(s1.getScheduleType());
            cTypeSchedule2.setSelectedItem(s2.getScheduleType());
            if (s1.getScheduleType().getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove1.setText(Utils.convertMasToStr(s1.getDays()));
                fDaysMove2.setText(Utils.convertMasToStr(s2.getDays()));
            }
            if (s1.getScheduleType().getId() == BusinessLogic.DAYS_WEEK) {
                fDaysMove1.setText(Utils.convertMasToDayOfWeek(s1.getDays()));
                fDaysMove2.setText(Utils.convertMasToDayOfWeek(s2.getDays()));
            }
        }
        setEnabledSheduleType();
        setVisible(true);
        return route;
    }

    private void setEnabledSheduleType() {
        if (cTypeSchedule1.getSelectedItem() != null) {
            fDaysMove1.setText("");
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK || ((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove1.setEnabled(true);
                fDaysMove1.setBackground(new Color(255, 255, 255));
            } else {
                fDaysMove1.setEnabled(false);
                fDaysMove1.setBackground(new Color(240, 240, 240));
            }
        }
        if (cTypeSchedule2.getSelectedItem() != null) {
            fDaysMove2.setText("");
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK || ((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove2.setEnabled(true);
                fDaysMove2.setBackground(new Color(255, 255, 255));

            } else {
                fDaysMove2.setEnabled(false);
                fDaysMove2.setBackground(new Color(240, 240, 240));

            }
        }
    }

    private boolean isCorrectInputData() {
        if (!fStationDeparture.getText().trim().equals("") &&
                !fStationDestination.getText().trim().equals("") &&
                !fNumberRoute1.getText().trim().equals("") &&
                !fNumberRoute2.getText().trim().equals("") &&
                !fTimeDeparture1.getText().trim().equals("") &&
                !fTimeDeparture2.getText().trim().equals("") &&
                !fTimeDestination1.getText().trim().equals("") &&
                !fTimeDestination2.getText().trim().equals("") &&
                (!fDaysMove1.isEnabled() || !fDaysMove1.getText().trim().equals("")) &&
                (!fDaysMove2.isEnabled() || !fDaysMove2.getText().trim().equals("")) &&
                !fHourMove1.getText().trim().equals("") &&
                !fHourMove2.getText().trim().equals("")) {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bCancel;
    public javax.swing.JButton bSave;
    private javax.swing.JComboBox cTypeSchedule1;
    private javax.swing.JComboBox cTypeSchedule2;
    private javax.swing.JTextField fDaysMove1;
    private javax.swing.JTextField fDaysMove2;
    public javax.swing.JFormattedTextField fHourMove1;
    public javax.swing.JFormattedTextField fHourMove2;
    public javax.swing.JTextField fNumberRoute1;
    public javax.swing.JTextField fNumberRoute2;
    public javax.swing.JTextField fStationDeparture;
    public javax.swing.JTextField fStationDestination;
    public javax.swing.JFormattedTextField fTimeDeparture1;
    public javax.swing.JFormattedTextField fTimeDeparture2;
    public javax.swing.JFormattedTextField fTimeDestination1;
    public javax.swing.JFormattedTextField fTimeDestination2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pLeft;
    // End of variables declaration//GEN-END:variables
}
