/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DEditTrain.java
 *
 * Created on 12.09.2010, 17:26:58
 */
package rzd.routeFleet;

import logic.BusinessLogic;
import rzd.model.objects.Route;

import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.StringTokenizer;
import javax.swing.*;

import rzd.model.objects.Shedule;
import rzd.model.objects.SheduleType;
import rzd.utils.Utils;

/**
 * @author ЧерныхЕА
 */
public class DRouteEdit extends javax.swing.JDialog {

    private ArrayList<SheduleType> sheduleTypes;
    private Route route;
    private JPopupMenu popupDayOfWeek;
    private JPopupMenu popupDayOfMonth;
    private PDayOfMonth pDayOfMonth;
    private PDaysOfWeek pDaysOfWeek;

    /**
     * Creates new form DEditTrain
     */
    public DRouteEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pDayOfMonth = new PDayOfMonth();
        pDaysOfWeek = new PDaysOfWeek();
        popupDayOfWeek = new JPopupMenu();
        popupDayOfMonth = new JPopupMenu();
        popupDayOfWeek.add(pDaysOfWeek);
        popupDayOfMonth.add(pDayOfMonth);
        for (int i = 0; i < 24; i++) {
            cHForward.addItem(i);
            cHBack.addItem(i);
        }
        for (int i = 0; i < 240; i++) {
            cHForwardInWay.addItem(i);
            cHBackInWay.addItem(i);
        }

        for (int i = 0; i < 60; i++) {
            cMForward.addItem(i);
            cMBack.addItem(i);
            cMForwardInWay.addItem(i);
            cMBackInWay.addItem(i);
        }

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLeft = new javax.swing.JPanel();
        bSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fNumberRoute1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fTimeForward = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        cTypeSchedule1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        fDaysMove1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fLengthForward = new javax.swing.JFormattedTextField();
        cHForward = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cMForward = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cHForwardInWay = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        cMForwardInWay = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fStationDeparture = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fStationDestination = new javax.swing.JTextField();
        bCancel = new javax.swing.JButton();
        cEnabled = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        fNumberRoute2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        fTimeBack = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        cTypeSchedule2 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        fDaysMove2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        fLengthBack = new javax.swing.JFormattedTextField();
        cHBack = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        cMBack = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        cHBackInWay = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        cMBackInWay = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Создание/редактирование расписания");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pLeft.setBackground(new java.awt.Color(250, 250, 250));

        bSave.setText("Сохранить");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)), "Следование из станции назначения в станцию отпрвления:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel7.setText("   Номер маршрута");
        jLabel7.setPreferredSize(new java.awt.Dimension(20, 14));

        fNumberRoute1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel3.setText("   Время отправления");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel8.setText("   Время в пути (в часах)");
        jLabel8.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel4.setText("   Время прибытия");
        jLabel4.setPreferredSize(new java.awt.Dimension(20, 14));

        fTimeForward.setBackground(new java.awt.Color(255, 255, 255));
        fTimeForward.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fTimeForward.setEditable(false);
        fTimeForward.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        fTimeForward.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel9.setText("   Тип следования");
        jLabel9.setPreferredSize(new java.awt.Dimension(20, 14));

        cTypeSchedule1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cTypeSchedule1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cTypeSchedule1ItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel11.setText("   Дни следования");
        jLabel11.setPreferredSize(new java.awt.Dimension(20, 14));

        fDaysMove1.setBackground(new java.awt.Color(255, 255, 255));
        fDaysMove1.setEditable(false);
        fDaysMove1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fDaysMove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fDaysMove1MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel17.setText("   Расстояние (км)");
        jLabel17.setPreferredSize(new java.awt.Dimension(20, 14));

        fLengthForward.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fLengthForward.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        cHForward.setFont(new java.awt.Font("Tahoma", 0, 12));
        cHForward.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate1(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("-часы");

        cMForward.setFont(new java.awt.Font("Tahoma", 0, 12));
        cMForward.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate1(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("-мин");

        cHForwardInWay.setFont(new java.awt.Font("Tahoma", 0, 12));
        cHForwardInWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate1(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel21.setText("-часы");

        cMForwardInWay.setFont(new java.awt.Font("Tahoma", 0, 12));
        cMForwardInWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate1(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel22.setText("-мин");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(fNumberRoute1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cTypeSchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fDaysMove1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fLengthForward, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fTimeForward, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cHForwardInWay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cHForward, 0, 61, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cMForwardInWay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cMForward, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNumberRoute1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHForward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cMForward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHForwardInWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(cMForwardInWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTimeForward, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTypeSchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fDaysMove1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fLengthForward, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        fStationDeparture.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fStationDeparture.setText("Москва");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel6.setText("   Станция отправления");
        jLabel6.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel16.setText("   Станция назначения");
        jLabel16.setPreferredSize(new java.awt.Dimension(20, 14));

        fStationDestination.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        bCancel.setText("Отмена");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        cEnabled.setBackground(new java.awt.Color(250, 250, 250));
        cEnabled.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cEnabled.setText("-активно");
        cEnabled.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cEnabledPropertyChange(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 0, 0));

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)), "Следование из станции назначения в станцию отпрвления:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(51, 51, 255));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel30.setText("   Номер маршрута");
        jLabel30.setPreferredSize(new java.awt.Dimension(20, 14));

        fNumberRoute2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel31.setText("   Время отправления");
        jLabel31.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel32.setText("   Время в пути (в часах)");
        jLabel32.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel33.setText("   Время прибытия");
        jLabel33.setPreferredSize(new java.awt.Dimension(20, 14));

        fTimeBack.setBackground(new java.awt.Color(255, 255, 255));
        fTimeBack.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        fTimeBack.setEditable(false);
        fTimeBack.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        fTimeBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel34.setText("   Тип следования");
        jLabel34.setPreferredSize(new java.awt.Dimension(20, 14));

        cTypeSchedule2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cTypeSchedule2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cTypeSchedule2ItemStateChanged(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel35.setText("   Дни следования");
        jLabel35.setPreferredSize(new java.awt.Dimension(20, 14));

        fDaysMove2.setBackground(new java.awt.Color(255, 255, 255));
        fDaysMove2.setEditable(false);
        fDaysMove2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fDaysMove2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fDaysMove2MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel36.setText("   Расстояние (км)");
        jLabel36.setPreferredSize(new java.awt.Dimension(20, 14));

        fLengthBack.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fLengthBack.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        cHBack.setFont(new java.awt.Font("Tahoma", 0, 12));
        cHBack.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate2(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel37.setText("-часы");

        cMBack.setFont(new java.awt.Font("Tahoma", 0, 12));
        cMBack.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate2(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel38.setText("-мин");

        cHBackInWay.setFont(new java.awt.Font("Tahoma", 0, 12));
        cHBackInWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate2(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel39.setText("-часы");

        cMBackInWay.setFont(new java.awt.Font("Tahoma", 0, 12));
        cMBackInWay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateDate2(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel40.setText("-мин");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("*");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel42.setForeground(new java.awt.Color(255, 0, 0));
        jLabel42.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(fNumberRoute2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cTypeSchedule2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fDaysMove2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fLengthBack, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fTimeBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cHBackInWay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cHBack, 0, 61, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cMBackInWay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cMBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNumberRoute2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(cMBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHBackInWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(cMBackInWay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTimeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTypeSchedule2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fDaysMove2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fLengthBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("*");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 13));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("-обязательное поле для заполнения");

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLeftLayout.createSequentialGroup()
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pLeftLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bSave)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pLeftLayout.createSequentialGroup()
                                .addComponent(cEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLeftLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(fStationDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel28)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(fStationDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)))
                .addContainerGap())
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLeftLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fStationDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fStationDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGap(7, 7, 7)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cEnabled)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSave)
                            .addComponent(bCancel))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap())))
        );

        getContentPane().add(pLeft);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        route = null;
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        route = null;
        setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed

    private void fDaysMove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fDaysMove1MouseClicked
        if (fDaysMove1.isEnabled()) {
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                popupDayOfMonth.show(fDaysMove1, evt.getX(), evt.getY());
                pDayOfMonth.setSelectedDays(Utils.convertStrToMas(fDaysMove1.getText()), fDaysMove1);
            }
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                popupDayOfWeek.show(fDaysMove1, evt.getX(), evt.getY());
                pDaysOfWeek.setSelectedDays(Utils.convertDayOfWeekToMas(fDaysMove1.getText()), fDaysMove1);
            }
        }
    }//GEN-LAST:event_fDaysMove1MouseClicked

    private void cTypeSchedule1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cTypeSchedule1ItemStateChanged
        setEnabledSheduleType1();
    }//GEN-LAST:event_cTypeSchedule1ItemStateChanged

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        if (isCorrectInputData()) {
            int[] days = null;
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                days = Utils.convertStrToMas(fDaysMove1.getText());
            } else {
                if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                    days = Utils.convertDayOfWeekToMas(fDaysMove1.getText());
                }
            }
            Shedule s1 = new Shedule(
                    route == null ? 0 : route.getSheduleForward().getId(),
                    Utils.convertStrToTime(cHForward.getSelectedItem().toString() + ":" + cMForward.getSelectedItem().toString()),
                    Utils.convertStrToTime(fTimeForward.getText()),
                    new Integer(cHForwardInWay.getSelectedItem().toString()),
                    new Integer(cMForwardInWay.getSelectedItem().toString()),
                    (SheduleType) cTypeSchedule1.getSelectedItem(),
                    days);
            days = null;
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                days = Utils.convertStrToMas(fDaysMove2.getText());
            } else {
                if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                    days = Utils.convertDayOfWeekToMas(fDaysMove2.getText());
                }
            }
            Shedule s2 = new Shedule(route == null ? 0 : route.getSheduleBack().getId(),
                    Utils.convertStrToTime(cHBack.getSelectedItem().toString() + ":" + cMBack.getSelectedItem().toString()),
                    Utils.convertStrToTime(fTimeBack.getText()),
                    new Integer(cHBackInWay.getSelectedItem().toString()),
                    new Integer(cMBackInWay.getSelectedItem().toString()),
                    (SheduleType) cTypeSchedule2.getSelectedItem(),
                    days);
            route = new Route(
                    route == null ? 0 : route.getId(),
                    fNumberRoute1.getText().trim(),
                    fNumberRoute2.getText().trim(),
                    fStationDeparture.getText().trim(),
                    fStationDestination.getText().trim(),
                    s1, s2, cEnabled.isSelected(),
                    new Integer(fLengthForward.getText()),
                    new Integer(fLengthBack.getText()));
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Заполните все поля");
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void cTypeSchedule2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cTypeSchedule2ItemStateChanged
        setEnabledSheduleType2();
    }//GEN-LAST:event_cTypeSchedule2ItemStateChanged

    private void fDaysMove2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fDaysMove2MouseClicked
        if (fDaysMove2.isEnabled()) {
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                popupDayOfMonth.show(fDaysMove2, evt.getX(), evt.getY());
                pDayOfMonth.setSelectedDays(Utils.convertStrToMas(fDaysMove2.getText()), fDaysMove2);
            }
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK) {
                popupDayOfWeek.show(fDaysMove2, evt.getX(), evt.getY());
                pDaysOfWeek.setSelectedDays(Utils.convertDayOfWeekToMas(fDaysMove2.getText()), fDaysMove2);
            }
        }
    }//GEN-LAST:event_fDaysMove2MouseClicked

    private void updateDate2(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updateDate2

        if (cMBack.getSelectedItem() != null && cMBackInWay.getSelectedItem() != null && cHBack.getSelectedItem() != null && cHBackInWay.getSelectedItem() != null) {
            int min = new Integer(cMBack.getSelectedItem().toString()) + new Integer(cMBackInWay.getSelectedItem().toString());
            int hh = new Integer(cHBack.getSelectedItem().toString()) + new Integer(cHBackInWay.getSelectedItem().toString());
            if (min > 59) {
                hh++;
                min = min - 60;
            }
            if (hh > 23) {
                hh = hh % 24;
            }
            fTimeBack.setText(new Integer(hh).toString() + ":" + new Integer(min).toString());
        }
    }//GEN-LAST:event_updateDate2

    private void cEnabledPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cEnabledPropertyChange
     if (cEnabled.isEnabled()) {
            jLabel25.setText("");
        } else {
            jLabel25.setText("Расписание не автивно, по данному расписанию поезда формироваться не будут!!!");
        }
    }//GEN-LAST:event_cEnabledPropertyChange

    private void updateDate1(java.awt.event.ItemEvent evt) {
        if (cMForward.getSelectedItem() != null && cMForwardInWay.getSelectedItem() != null && cHForward.getSelectedItem() != null && cHForwardInWay.getSelectedItem() != null) {
            int min = new Integer(cMForward.getSelectedItem().toString()) + new Integer(cMForwardInWay.getSelectedItem().toString());
            int hh = new Integer(cHForward.getSelectedItem().toString()) + new Integer(cHForwardInWay.getSelectedItem().toString());
            if (min > 59) {
                hh++;
                min = min - 60;
            }
            if (hh > 23) {
                hh = hh % 24;
            }
            fTimeForward.setText(new Integer(hh).toString() + ":" + new Integer(min).toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DRouteEdit dialog = new DRouteEdit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Route open(Route route, ArrayList<SheduleType> sheduleTypes) {
        if (sheduleTypes == null) {
            JOptionPane.showMessageDialog(null, "Справочник типов расписаний пуст");
            return null;
        }
        this.route = route;
        this.sheduleTypes = sheduleTypes;
        cTypeSchedule1.removeAllItems();
        cTypeSchedule2.removeAllItems();
        for (SheduleType st : sheduleTypes) {
            cTypeSchedule2.addItem(st);
            cTypeSchedule1.addItem(st);
        }
        setEnabledSheduleType1();
        setEnabledSheduleType2();
        if (route == null) {
            fDaysMove1.setText("");
            fDaysMove2.setText("");
            cHForwardInWay.setSelectedIndex(0);
            cHBackInWay.setSelectedIndex(0);
            cMForwardInWay.setSelectedIndex(0);
            cMBackInWay.setSelectedIndex(0);
            cHForward.setSelectedIndex(0);
            cHBack.setSelectedIndex(0);
            cMForward.setSelectedIndex(0);
            cMBack.setSelectedIndex(0);
            fNumberRoute1.setText("");
            fNumberRoute2.setText("");
            fStationDeparture.setText("");
            fStationDestination.setText("");
            fTimeForward.setText("");
            fTimeBack.setText("");
            fLengthForward.setText("");
            fLengthBack.setText("");
            cEnabled.setSelected(true);

        } else {
            Shedule s1 = route.getSheduleForward();
            Shedule s2 = route.getSheduleBack();
            fStationDeparture.setText(route.getCityFrom());
            fStationDestination.setText(route.getCityTo());
            fNumberRoute1.setText(route.getNumberForward());
            fNumberRoute2.setText(route.getNumberBack());
            StringTokenizer t = new StringTokenizer(Utils.convertTimeToStr(s1.getTimeDeparture()), ":");
            String hh = t.nextToken();
            String mm = t.nextToken();
            cHForward.setSelectedItem(new Integer(hh));
            cMForward.setSelectedItem(new Integer(mm));
            t = new StringTokenizer(Utils.convertTimeToStr(s2.getTimeDeparture()), ":");
            hh = t.nextToken();
            mm = t.nextToken();
            cHBack.setSelectedItem(new Integer(hh));
            cMBack.setSelectedItem(new Integer(mm));
            //todo Ошибка возвращается 1 за место 0
            cHForwardInWay.setSelectedItem(s1.getHoursTimeInWay());
            cMForwardInWay.setSelectedItem(s1.getMinutesTimeInWay());
            cHBackInWay.setSelectedItem(s2.getHoursTimeInWay());
            cMBackInWay.setSelectedItem(s2.getMinutesTimeInWay());
            fTimeForward.setText(Utils.convertTimeToStr(s1.getTimeDestination()));
            fTimeBack.setText(Utils.convertTimeToStr(s2.getTimeDestination()));
            cTypeSchedule1.setSelectedItem(s1.getSheduleType());
            cTypeSchedule2.setSelectedItem(s2.getSheduleType());
            if (s1.getSheduleType().getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove1.setText(Utils.convertMasToStr(s1.getDays()));
            }
            if (s1.getSheduleType().getId() == BusinessLogic.DAYS_WEEK) {
                fDaysMove1.setText(Utils.convertMasToDayOfWeek(s1.getDays()));
            }
            if (s2.getSheduleType().getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove2.setText(Utils.convertMasToStr(s2.getDays()));
            }
            if (s2.getSheduleType().getId() == BusinessLogic.DAYS_WEEK) {
                fDaysMove2.setText(Utils.convertMasToDayOfWeek(s2.getDays()));
            }
            fLengthForward.setText(new Integer(route.getLengthForward()).toString());
            fLengthBack.setText(new Integer(route.getLengthBack()).toString());
            cEnabled.setSelected(route.isEnabled());
        }
        setVisible(true);
        return this.route;
    }

    private void setEnabledSheduleType1() {
        if (cTypeSchedule1.getSelectedItem() != null) {
            fDaysMove1.setText("");
            if (((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK || ((SheduleType) cTypeSchedule1.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove1.setEnabled(true);
                fDaysMove1.setBackground(new Color(255, 255, 255));
            } else {
                fDaysMove1.setEnabled(false);
                fDaysMove1.setBackground(new Color(240, 240, 240));
            }
        }
    }


    private void setEnabledSheduleType2() {
        if (cTypeSchedule2.getSelectedItem() != null) {
            fDaysMove2.setText("");
            if (((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_WEEK || ((SheduleType) cTypeSchedule2.getSelectedItem()).getId() == BusinessLogic.DAYS_MONTH) {
                fDaysMove2.setEnabled(true);
                fDaysMove2.setBackground(new Color(255, 255, 255));
            } else {
                fDaysMove2.setEnabled(false);
                fDaysMove2.setBackground(new Color(240, 240, 240));

            }
        }
    }

    private boolean isCorrectInputData() {
        if (!fStationDeparture.getText().trim().equals("") &&
                !fStationDestination.getText().trim().equals("") &&
                !fNumberRoute1.getText().trim().equals("") &&
                !fNumberRoute2.getText().trim().equals("") &&
                !fTimeForward.getText().trim().equals("") &&
                !fTimeBack.getText().trim().equals("") &&
                (!fDaysMove1.isEnabled() || !fDaysMove1.getText().trim().equals("")) &&
                (!fDaysMove2.isEnabled() || !fDaysMove2.getText().trim().equals("")) &&
                !fLengthForward.getText().trim().equals("") &&
                !fLengthBack.getText().trim().equals("")) {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bCancel;
    public javax.swing.JButton bSave;
    private javax.swing.JCheckBox cEnabled;
    private javax.swing.JComboBox cHBack;
    private javax.swing.JComboBox cHBackInWay;
    private javax.swing.JComboBox cHForward;
    private javax.swing.JComboBox cHForwardInWay;
    private javax.swing.JComboBox cMBack;
    private javax.swing.JComboBox cMBackInWay;
    private javax.swing.JComboBox cMForward;
    private javax.swing.JComboBox cMForwardInWay;
    private javax.swing.JComboBox cTypeSchedule1;
    private javax.swing.JComboBox cTypeSchedule2;
    private javax.swing.JTextField fDaysMove1;
    private javax.swing.JTextField fDaysMove2;
    public javax.swing.JFormattedTextField fLengthBack;
    public javax.swing.JFormattedTextField fLengthForward;
    public javax.swing.JTextField fNumberRoute1;
    public javax.swing.JTextField fNumberRoute2;
    public javax.swing.JTextField fStationDeparture;
    public javax.swing.JTextField fStationDestination;
    public javax.swing.JFormattedTextField fTimeBack;
    public javax.swing.JFormattedTextField fTimeForward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pLeft;
    // End of variables declaration//GEN-END:variables
}
