/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DCarLocation.java
 *
 * Created on 14.10.2010, 23:07:45
 */
package rzd.carFleet;

import java.util.ArrayList;
import logic.BusinessLogic;
import rzd.model.Model;
import rzd.model.objects.Car;
import rzd.model.objects.CarLocation;
import rzd.model.objects.Repair;
import rzd.model.objects.RepairType;
import rzd.model.objects.Road;
import rzd.model.objects.RoadType;
import rzd.model.objects.structure.CarLocationStructure;

/**
 *
 * @author Евгений
 */
public class DCarLocation extends javax.swing.JDialog {

    /** Creates new form DCarLocation */
    public DCarLocation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cLocation = new javax.swing.JComboBox();
        pRepair = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cOnRoad = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cTypeRepair = new javax.swing.JComboBox();
        pRoad = new javax.swing.JPanel();
        cRoad = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cTypeRoad = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tComment = new javax.swing.JTextArea();
        bCancel = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setText("Местоположение вагона");

        cLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cLocationItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        jLabel6.setText("Ремонт на наших путях");

        cOnRoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOnRoadActionPerformed(evt);
            }
        });

        jLabel3.setText("Тип ремонта");

        javax.swing.GroupLayout pRepairLayout = new javax.swing.GroupLayout(pRepair);
        pRepair.setLayout(pRepairLayout);
        pRepairLayout.setHorizontalGroup(
            pRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRepairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(pRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cTypeRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cOnRoad))
                .addContainerGap())
        );
        pRepairLayout.setVerticalGroup(
            pRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRepairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cTypeRepair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cOnRoad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pRepair);

        jLabel2.setText("Путь");

        cTypeRoad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cTypeRoadItemStateChanged(evt);
            }
        });

        jLabel4.setText("Тип пути");

        javax.swing.GroupLayout pRoadLayout = new javax.swing.GroupLayout(pRoad);
        pRoad.setLayout(pRoadLayout);
        pRoadLayout.setHorizontalGroup(
            pRoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRoadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(88, 88, 88)
                .addGroup(pRoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cRoad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cTypeRoad, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        pRoadLayout.setVerticalGroup(
            pRoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRoadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cTypeRoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cRoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pRoad);

        tComment.setColumns(20);
        tComment.setRows(5);
        jScrollPane1.setViewportView(tComment);

        bCancel.setText("Отмена");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bSave.setText("Сохранить");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Комментарий");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(110, 110, 110)
                .addComponent(jLabel5)
                .addGap(175, 175, 175))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(bSave)
                .addGap(18, 18, 18)
                .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCancel)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_bSaveActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCancelActionPerformed

    private void cLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cLocationItemStateChanged
        if (BusinessLogic.UNKNOWN == ((CarLocation) evt.getItem()).getIdLocation()) {
            pRoad.setVisible(false);
            pRepair.setVisible(false);
        }

        if (BusinessLogic.REPAIR == ((CarLocation) evt.getItem()).getIdLocation()) {
            pRoad.setVisible(false);
            pRepair.setVisible(true);
            cOnRoad.setSelected(false);
            cTypeRepair.removeAllItems();
            ArrayList<RepairType> repairTypes = Model.getModel().getRepairTypes();
            if (repairTypes != null) {
                for (RepairType repairType : repairTypes) {
                    cTypeRepair.addItem(repairType);
                }
            }
        }
        if (BusinessLogic.ON_ROAD == ((CarLocation) evt.getItem()).getIdLocation()) {
            pRoad.setVisible(true);
            pRepair.setVisible(false);
            cTypeRoad.removeAllItems();
            ArrayList<RoadType> roadTypes = Model.getModel().getRoadTypes();
            if (roadTypes != null) {
                for (RoadType roadType : roadTypes) {
                    cTypeRoad.addItem(roadType);
                }
            }
        }
    }//GEN-LAST:event_cLocationItemStateChanged

    private void cTypeRoadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cTypeRoadItemStateChanged
        cRoad.removeAllItems();
        ArrayList<Road> roads = Model.getModel().getRoadsByType((RoadType) evt.getItem());
        if (roads != null) {
            for (Road road : roads) {
                cRoad.addItem(road);
            }
        }
    }//GEN-LAST:event_cTypeRoadItemStateChanged

    private void cOnRoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOnRoadActionPerformed
         pRoad.setVisible(cOnRoad.isSelected());
    }//GEN-LAST:event_cOnRoadActionPerformed

    public CarLocationStructure open(Car car) {
        if (car == null) {
            return null;
        }
        ArrayList<CarLocation> carLocations = Model.getModel().getCarLocations();
        cLocation.removeAllItems();
        if (carLocations != null && carLocations.size() > 0) {
            for (CarLocation carLocation : carLocations) {
                cLocation.addItem(carLocation);
            }
            CarLocation carLocation = car.getCarLocation();
            cLocation.setSelectedItem(carLocation);
            if (BusinessLogic.ON_ROAD == carLocation.getIdLocation()) {
                Road road = Model.getModel().getRoadByCar(car);
                if (road != null) {
                    cTypeRoad.setSelectedItem(road.getRoadType());
                    cRoad.setSelectedItem(road);
                }
            }
            if (BusinessLogic.REPAIR == carLocation.getIdLocation()) {
//              ArrayList<RepairType> repairTypes = car.getCarLocation();
//            if (repairTypes != null) {
//                for (RepairType repairType : repairTypes) {
//                    cTypeRepair.addItem(repairType);
//                }
//            }
            }
        }
        setVisible(true);
        Road road = null;
        Repair repair = null;
        if (BusinessLogic.ON_ROAD == ((CarLocation) cLocation.getSelectedItem()).getIdLocation()) {
            road = (Road) cRoad.getSelectedItem();
        }
        if (BusinessLogic.REPAIR == ((CarLocation) cLocation.getSelectedItem()).getIdLocation()) {
            if (cOnRoad.isSelected()) {
                repair = new Repair(0, (RepairType) cTypeRepair.getSelectedItem(), car, (Road) cRoad.getSelectedItem(), null, null);
            } else {
                repair = new Repair(0, (RepairType) cTypeRepair.getSelectedItem(), car, null, null, null);
            }
        }

        return new CarLocationStructure(car, road, repair);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DCarLocation dialog = new DCarLocation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox cLocation;
    private javax.swing.JCheckBox cOnRoad;
    private javax.swing.JComboBox cRoad;
    private javax.swing.JComboBox cTypeRepair;
    private javax.swing.JComboBox cTypeRoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pRepair;
    private javax.swing.JPanel pRoad;
    private javax.swing.JTextArea tComment;
    // End of variables declaration//GEN-END:variables
}
